title: "Zenburn! Please: Test"
author: "RZN"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed

markdown: kramdown
highlighter: rouge
kramdown:
  toc_levels: 1..4
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
